github:[ferrariguy]
custom: ["https://www.paypal.com/donate/?business=PXY7769HB3QWN&no_recurring=0&item_name=Thanks+for+the+support+or+appreciation+of+whichever+object%2Fcode%2Fetc+I%27ve+published.&currency_code=USD"]